server:
  port: 8080

spring:
  application:
    name: Writer

  datasource:
    url: jdbc:mysql://localhost:3306/cqrs
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PASSWORD

  jpa:
    hibernate:
      ddl-auto: update # Entity 클래스를 기준으로 테이블이 자동 생성 및 수정됨
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.type.description.sql: trace
